FROM node:16.13.0-alpine3.14

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .


ARG API_KEY
ARG SENTRY_DSN
ARG SENTRY_SAMPLE_RATE
ARG SENTRY_ENABLED
ARG GOOGLE_ANALYTICS_ID
ARG NEW_RELIC_APP_NAME
ARG NEW_RELIC_LICENSE_KEY
ARG NEW_RELIC_ACCOUNT_ID
ARG NEW_RELIC_BROWSER_LICENSE_KEY
ARG NEW_RELIC_APPLICATION_ID
ARG BASE_URL_ADUAN
ARG USERNAME_URL_ADUAN
ARG PASSWORD_URL_ADUAN
ARG KEYCLOAK_URL
ARG KEYCLOAK_CLIENT_ID_PARTNER
ARG KEYCLOAK_CLIENT_SECRET_PARTNER
ARG X_PARTNER_ID
ARG GOOGLE_MAPS_API
ARG URL_FILE
ARG NODE_ENV
ARG UNLEASH_URL
ARG UNLEASH_TOKEN


ENV API_KEY $API_KEY
ENV SENTRY_DSN $SENTRY_DSN
ENV SENTRY_SAMPLE_RATE $SENTRY_SAMPLE_RATE
ENV SENTRY_ENABLED $SENTRY_ENABLED
ENV HOST 0.0.0.0
ENV PORT 3000
ENV GOOGLE_ANALYTICS_ID $GOOGLE_ANALYTICS_ID
ENV NEW_RELIC_APP_NAME $NEW_RELIC_APP_NAME
ENV NEW_RELIC_LICENSE_KEY $NEW_RELIC_LICENSE_KEY
ENV NEW_RELIC_ACCOUNT_ID $NEW_RELIC_ACCOUNT_ID
ENV NEW_RELIC_BROWSER_LICENSE_KEY $NEW_RELIC_BROWSER_LICENSE_KEY
ENV NEW_RELIC_APPLICATION_ID $NEW_RELIC_APPLICATION_ID
ENV BASE_URL_ADUAN $BASE_URL_ADUAN
ENV USERNAME_URL_ADUAN $USERNAME_URL_ADUAN
ENV PASSWORD_URL_ADUAN $PASSWORD_URL_ADUAN
ENV KEYCLOAK_URL $KEYCLOAK_URL
ENV KEYCLOAK_CLIENT_ID_PARTNER $KEYCLOAK_CLIENT_ID_PARTNER
ENV KEYCLOAK_CLIENT_SECRET_PARTNER $KEYCLOAK_CLIENT_SECRET_PARTNER
ENV X_PARTNER_ID $X_PARTNER_IDX_PARTNER_ID
ENV GOOGLE_MAPS_API $GOOGLE_MAPS_API
ENV URL_FILE $URL_FILE
ENV NODE_ENV $NODE_ENV
ENV UNLEASH_URL $UNLEASH_URL
ENV UNLEASH_TOKEN $UNLEASH_TOKEN

RUN npm run build

EXPOSE 3000

CMD [ "npm", "start" ]
