FROM node:16.13.0-alpine3.14

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .


ARG API_KEY
ARG SENTRY_DSN
ARG SENTRY_SAMPLE_RATE
ARG SENTRY_ENABLED
ARG GOOGLE_ANALYTICS_ID
ARG NEW_RELIC_APP_NAME
ARG NEW_RELIC_LICENSE_KEY
ARG NEW_RELIC_ACCOUNT_ID
ARG NEW_RELIC_BROWSER_LICENSE_KEY
ARG NEW_RELIC_APPLICATION_ID
ARG BASE_URL_ADUAN
ARG USERNAME_URL_ADUAN
ARG PASSWORD_URL_ADUAN
ARG LINK_SAPAWARGA_ANDROID
ARG LINK_SAPAWARGA_IOS
ENV API_KEY $API_KEY
ENV SENTRY_DSN $SENTRY_DSN
ENV SENTRY_SAMPLE_RATE $SENTRY_SAMPLE_RATE
ENV SENTRY_ENABLED $SENTRY_ENABLED
ENV HOST 0.0.0.0
ENV PORT 3000
ENV GOOGLE_ANALYTICS_ID $GOOGLE_ANALYTICS_ID
ENV NEW_RELIC_APP_NAME $NEW_RELIC_APP_NAME
ENV NEW_RELIC_LICENSE_KEY $NEW_RELIC_LICENSE_KEY
ENV NEW_RELIC_ACCOUNT_ID $NEW_RELIC_ACCOUNT_ID
ENV NEW_RELIC_BROWSER_LICENSE_KEY $NEW_RELIC_BROWSER_LICENSE_KEY
ENV NEW_RELIC_APPLICATION_ID $NEW_RELIC_APPLICATION_ID
ENV BASE_URL_ADUAN $BASE_URL_ADUAN
ENV USERNAME_URL_ADUAN $USERNAME_URL_ADUAN
ENV PASSWORD_URL_ADUAN $PASSWORD_URL_ADUAN
ENV LINK_SAPAWARGA_ANDROID $LINK_SAPAWARGA_ANDROID
ENV LINK_SAPAWARGA_IOS $LINK_SAPAWARGA_IOS

RUN npm run build

EXPOSE 3000

CMD [ "npm", "start" ]
